version: '2'
# 定义四个服务nginx,php,mysql,redis
services:
  # REDIS
  pm2:
    build: ./
    environment:
      APP: pm2.json
      WATCH: "false"
      GLOBALPACKAGE:"yarn ts-node"
    ports:
      - "80:80"
      - "443:443"   
    volumes:
      - ./app:/app
    restart: always
    container_name: node-pm2
networks:
  frontend:
  backend:
