#!/bin/bash

if [ -z "$APP" ]; then
    export APP=app.js
fi

if [ -z "$WATCH" ]; then
    export WATCH=false
fi

npm i -g yarn pm2

COMMAND="pm2 start -x $APP --no-daemon"

if [ "$WATCH" == "true" ]; then
    COMMAND=$COMMAND" --watch"
fi
if [ -z "$GLOBALPACKAGE" ]; then
    npm i -g $GLOBALPACKAGE
fi
cd /app
yarn
$COMMAND
